### ISSUE TITLE
ch03  不同粒度模型剪枝 文件损坏

### ISSUE THREAD

**Issue by KMnO4-zx** [bupt-ai-club/awesome-compression#1]
- ch03  不同粒度模型剪枝 文件损坏
- 为啥ch02 是 手写数字识别啊？课程内容没有这个叭？

**Comment by ironartisan** [comment]
@KMnO4-zx 感谢反馈，教程虽然借鉴了MIT 6.5940，但不是简单的翻译，做了很多改动，补充了相关基础知识，所以有很多内容不一致的地方
